### ISSUE TITLE
An issue on my Android 6.0 phone

### ISSUE THREAD

**Issue by ghost** [OneUIProject/oneui-design#43] opened 2024-07-22 11:55 UTC
The app supports Android 6.0 and above. It has been tested on an Android 6.0 phone with the language set to English, and everything works fine except for when clicking on Color in Pickers section or ColorPickerPreference in preferences, which results in the message "Unfortunately, OneUI Sample has stopped" appearing on the phone. Note that my Android 6.0 phone isn’t a Samsung phone, Thanks to you for this amazing Project

**Comment by Yanndroid** [comment] 2024-07-22 12:30
Hey there,
Android 6 is quite old, so my guess would be, it's calling an unsupported method, thus crashing the app. I don't have any Android 6 devices anymore, so I can't test it. Do you know how to take logs on Android?

**Comment by Yanndroid** [comment] 2024-07-22 12:34
Closing because author's account got deleted 30min after opening this issue.

**Closed as completed by Yanndroid** 2024-07-22 12:34 UTC

**Comment by tribalfs** [comment] 2024-07-22 13:30
Hi @Yanndroid .  I was able to look on this previously. This issue is caused by [SeslColorPicker  ](https://github.com/OneUIProject/oneui-core/blob/8c7734aeb9c89cdd74f814e96952709515370142/picker/picker-color/src/main/java/androidx/picker3/widget/SeslColorPicker.java#L878) calling [GradientDrawable.getColor()](https://developer.android.com/reference/android/graphics/drawable/GradientDrawable#getColor()) which is only available starting api 24.
